// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    IFaArrowsAlt: typeof import('~icons/fa/arrows-alt')['default']
    IFaBars: typeof import('~icons/fa/bars')['default']
    IFaBold: typeof import('~icons/fa/bold')['default']
    IFaCode: typeof import('~icons/fa/code')['default']
    IFaColumns: typeof import('~icons/fa/columns')['default']
    IFaCompress: typeof import('~icons/fa/compress')['default']
    IFaEye: typeof import('~icons/fa/eye')['default']
    IFaEyeSlash: typeof import('~icons/fa/eye-slash')['default']
    IFaFloppyO: typeof import('~icons/fa/floppy-o')['default']
    IFaHashtag: typeof import('~icons/fa/hashtag')['default']
    IFaItalic: typeof import('~icons/fa/italic')['default']
    IFaLink: typeof import('~icons/fa/link')['default']
    IFaListOl: typeof import('~icons/fa/list-ol')['default']
    IFaListUl: typeof import('~icons/fa/list-ul')['default']
    IFaPictureO: typeof import('~icons/fa/picture-o')['default']
    IFaQuoteLeft: typeof import('~icons/fa/quote-left')['default']
    IFaRepeat: typeof import('~icons/fa/repeat')['default']
    IFaStrikethrough: typeof import('~icons/fa/strikethrough')['default']
    IFaSubscript: typeof import('~icons/fa/subscript')['default']
    IFaSuperscript: typeof import('~icons/fa/superscript')['default']
    IFaTable: typeof import('~icons/fa/table')['default']
    IFaTimes: typeof import('~icons/fa/times')['default']
    IFaUnderline: typeof import('~icons/fa/underline')['default']
    IFaUndo: typeof import('~icons/fa/undo')['default']
    IFaWindowMaximize: typeof import('~icons/fa/window-maximize')['default']
    MdToolbarLeft: typeof import('./src/components/md-toolbar-left.vue')['default']
    MdToolbarRight: typeof import('./src/components/md-toolbar-right.vue')['default']
  }
}

export { }
